In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
% cd gdrive/MyDrive/project_sp/drnn

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/MyDrive/project_sp/drnn


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

import tensorflow.compat.v2 as tf
#tf.enable_v2_behavior()

import tensorflow_probability as tfp
tfd = tfp.distributions
import pandas as pd

#to make matplotlib output appear in notebook
%matplotlib inline

from models import model_gamma
from utils import utils
from utils import plots
from utils import overhead

In [ ]:
gpu_devices = tf.config.experimental.list_physical_devices('GPU')
for device in gpu_devices:
    tf.config.experimental.set_memory_growth(device, True)

In [ ]:
#loss function
negloglik = lambda y, p_y: -p_y.log_prob(y)
loss_fun = negloglik
# How large is the dataset?
N = 15000
# number of epochs to train the model for
max_num_epochs = 1500
# define batch size for training
batch_size = 256
# maximum number of hidden units for random search
max_hidden_units = 1800
# learning rate
lr = 0.001
# number hidden layers
max_num_hidden_layers = 10
#number of predictors
k = 5
#number of sets for random search
num_sets = 150

#filetype
filename = "expgamma5d"
num_files = 5

#model type
modeltype = model_gamma

#random seed
rdseed = 2012

#optimizer
optimer = tf.keras.optimizers.Adam
activation_fun = 'relu'

#schedule
schedule = True
earlystop = True
pat = 10

In [ ]:
hu_key = overhead.fitsimdat(num_sets = num_sets, max_num_hidden_layers = max_num_hidden_layers, 
            max_hidden_units = max_hidden_units, rdseed = rdseed,
            filename = filename, num_files = num_files, k = k, modeltype = modeltype, 
            activation_fun = activation_fun, loss_fun = loss_fun, optimer = optimer,
            lr = lr, batch_size = batch_size, max_num_epochs = max_num_epochs, 
            schedule = schedule, earlystop = earlystop, pat = pat,
            distr = "gamma", save = True)

doing 1th dataset
[746. 484. 270.]
[391. 503. 401. 231.]
[1242.  648.  580.  300.]
[573. 743. 641. 440. 316. 244. 223.]
[428. 368. 314. 191. 190. 126.]
[1173. 1202.]
[1479. 1597. 1681.  972.  817.  500.]
[1395. 1751.]
[220. 150. 107.  53.  31.  19.  15.  13.]
[833. 420. 271. 179. 121. 102.]
[243. 398. 507. 732. 462. 344.]
[ 825.  872. 1648. 1059.  705.  654.  562.  434.  242.  133.]
[1527.]
[ 866. 1266.  829.  691.]
[575. 614. 930. 731. 406. 378. 352. 202.]
[ 358.  547. 1044.  929.  567.  355.  283.  206.]
[ 915. 1612.  948.  796.  541.  315.  282.  278.  258.  134.]
[333. 646. 850. 824. 638. 584.]
[528. 492. 464. 266. 164.]
[216. 281. 524. 953. 726. 474. 427. 256.]
[1483. 1601. 1359.  733.]
[1088.  720.  579.]
[356. 684. 351. 290. 279.]
[ 906. 1429.  859.  798.  643.  328.  263.  208.]
[ 515.  732. 1249. 1695. 1111.  788.  535.]
[ 953. 1470. 1480.  765.  762.  476.  307.  264.  249.]
[57. 37.]
[111. 119. 212. 344. 216. 182. 137.  82.  80.  51.]
[900.]
[210. 347. 444. 392. 279. 249. 21

In [ ]:
hu_key

filename  ... is_min
0    expgamma5d_1  ...      0
1    expgamma5d_1  ...      0
2    expgamma5d_1  ...      0
3    expgamma5d_1  ...      0
4    expgamma5d_1  ...      0
..            ...  ...    ...
145  expgamma5d_5  ...      0
146  expgamma5d_5  ...      0
147  expgamma5d_5  ...      0
148  expgamma5d_5  ...      0
149  expgamma5d_5  ...      0

[750 rows x 4 columns]

In [ ]:
hu_key2 = overhead.fitsimdat(num_sets = num_sets, max_num_hidden_layers = max_num_hidden_layers, 
            max_hidden_units = max_hidden_units, rdseed = rdseed,
            filename = filename, num_files = num_files, k = k, modeltype = modeltype, 
            activation_fun = activation_fun, loss_fun = loss_fun, optimer = optimer,
            lr = lr, batch_size = batch_size, max_num_epochs = max_num_epochs, 
            schedule = schedule, earlystop = earlystop, pat = pat,
            distr = "gamma", save = True, startkj = 5)

doing 6th dataset
[746. 484. 270.]
[391. 503. 401. 231.]
[1242.  648.  580.  300.]
[573. 743. 641. 440. 316. 244. 223.]
[428. 368. 314. 191. 190. 126.]
[1173. 1202.]
[1479. 1597. 1681.  972.  817.  500.]
[1395. 1751.]
[220. 150. 107.  53.  31.  19.  15.  13.]
[833. 420. 271. 179. 121. 102.]
[243. 398. 507. 732. 462. 344.]
[ 825.  872. 1648. 1059.  705.  654.  562.  434.  242.  133.]
[1527.]
[ 866. 1266.  829.  691.]
[575. 614. 930. 731. 406. 378. 352. 202.]
[ 358.  547. 1044.  929.  567.  355.  283.  206.]
[ 915. 1612.  948.  796.  541.  315.  282.  278.  258.  134.]
[333. 646. 850. 824. 638. 584.]
[528. 492. 464. 266. 164.]
[216. 281. 524. 953. 726. 474. 427. 256.]
[1483. 1601. 1359.  733.]
[1088.  720.  579.]
[356. 684. 351. 290. 279.]
[ 906. 1429.  859.  798.  643.  328.  263.  208.]
[ 515.  732. 1249. 1695. 1111.  788.  535.]
[ 953. 1470. 1480.  765.  762.  476.  307.  264.  249.]
[57. 37.]
[111. 119. 212. 344. 216. 182. 137.  82.  80.  51.]
[900.]
[210. 347. 444. 392. 279. 249. 21