In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
% cd gdrive/MyDrive/project_sp/drnn

Mounted at /content/gdrive
/content/gdrive/MyDrive/project_sp/drnn


In [2]:
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

import tensorflow.compat.v2 as tf
#tf.enable_v2_behavior()

import tensorflow_probability as tfp
tfd = tfp.distributions
import pandas as pd

#to make matplotlib output appear in notebook
%matplotlib inline

from models import model_normal
from utils import utils
from utils import plots
from utils import overhead

In [3]:
#loss function
negloglik = lambda y, p_y: -p_y.log_prob(y)
loss_fun = negloglik
# How large is the dataset?
N = 15000
# number of epochs to train the model for
max_num_epochs = 2000
# define batch size for training
batch_size = 256
# maximum number of hidden units for random search
max_hidden_units = 1800
# learning rate
lr = 0.0005
# number hidden layers
max_num_hidden_layers = 10
#number of predictors
k = 10
#number of sets for random search
num_sets = 150

#filetype
filename = "expnormal10d"
num_files = 10

#model type
modeltype = model_normal

#random seed
rdseed = 20125

#optimizer
optimer = tf.keras.optimizers.Adam
activation_fun = 'relu'

#schedule
schedule = True
earlystop = True
pat = 30

In [4]:
modeltype

<module 'models.model_normal' from '/content/gdrive/MyDrive/project_sp/drnn/models/model_normal.py'>

In [5]:
hu_key = overhead.fitsimdat(num_sets = num_sets, max_num_hidden_layers = max_num_hidden_layers, 
            max_hidden_units = max_hidden_units, rdseed = rdseed,
            filename = filename, num_files = num_files, k = k, modeltype = modeltype, 
            activation_fun = activation_fun, loss_fun = loss_fun, optimer = optimer,
            lr = lr, batch_size = batch_size, max_num_epochs = max_num_epochs, 
            schedule = schedule, earlystop = earlystop, pat = pat,
            distr = "normal", save = True)

doing 1th dataset
<module 'models.model_normal' from '/content/gdrive/MyDrive/project_sp/drnn/models/model_normal.py'>
in fitsimdat:normal
in opt_hunormal
[ 982. 1458.]
[ 889. 1596. 1412.  948.  501.]
[254. 288. 349. 253. 206. 184.]
[ 594.  826. 1302. 1462. 1478. 1292.  888.  502.  336.]
[1096. 1147. 1745. 1333.  845.]
[1134. 1314. 1473.  967.  594.  573.]
[1319. 1684. 1576.]
[1679. 1555.]
[109. 182. 362. 202. 124. 117.]
[1256.  910.]
[ 629.  662.  934. 1052.  720.  560.]
[ 947. 1487. 1024.]
[102. 128.  96.  88.  66.  65.  50.  30.]
[324. 341. 648. 353. 332. 249. 193. 131.]
[ 404.  530. 1013. 1696. 1250.  816.]
[ 672.  794.  888. 1113.  651.  555.]
[1391.]
[ 24.  39.  78. 152. 157. 140.  97.  49.]
[521. 880. 883. 461.]
[ 220.  318.  376.  635. 1248.  944.  713.  506.  362.  283.]
[307.]
[149. 227. 166.  84.  49.  36.  26.  25.  17.  10.]
[394. 478. 516. 961. 582. 409. 337. 207. 175.]
[1128. 1753.]
[412. 458.]
[341. 428. 612. 884. 644. 565.]
[1329.]
[1414. 1589.  892.]
[ 964. 1024. 1047